SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_OUTS A JOIN ANIMAL_INS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.SEX_UPON_INTAKE LIKE 'INTACT%'
AND (A.SEX_UPON_OUTCOME LIKE 'SPAYED%'
    OR A.SEX_UPON_OUTCOME LIKE 'NEUTERED%')
ORDER BY A.ANIMAL_ID