SELECT D.HOUR, NVL(COUNT, 0) AS COUNT
FROM (SELECT TO_CHAR(DATETIME,'HH24') AS HOUR, COUNT(*) AS COUNT
        FROM ANIMAL_OUTS
        GROUP BY TO_CHAR(DATETIME,'HH24')
        ORDER BY HOUR) O,
        (SELECT LEVEL-1 AS HOUR FROM DUAL CONNECT BY LEVEL <=24) D
WHERE D.HOUR = O.HOUR(+)
ORDER BY D.HOUR;