SELECT SUM(SCORE) AS SCORE, A.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL 
FROM HR_GRADE A JOIN HR_EMPLOYEES B ON B.EMP_NO = A.EMP_NO
GROUP BY YEAR, EMP_NO
HAVING A.YEAR = '2022'
ORDER BY SCORE DESC
LIMIT 1